#!/bin/bash
eval "$(cat $(dirname "${BASH_SOURCE[0]}")/header.sh)"
container=vnc_dev
tag=latest
command="/default_exec_entry.sh"
if [ ! -z $1 ]; then
    container=$1
fi
if [ ! -z $2 ]; then
    tag=$2
fi
if [ ! -z $3 ]; then
    command=$3
fi

docker exec -it ${container}_${tag} ${command}
