#!/bin/bash
eval "$(cat $(dirname "${BASH_SOURCE[0]}")/header.sh)"
container=base_dev
tag=latest
if [ ! -z $1 ]; then
    container=$1
fi
if [ ! -z $2 ]; then
    tag=$2
fi
docker run ${STANDARD_MOUNTING_ARGUMENTS} -it ${container}:${tag}
