#!/bin/bash
eval "$(cat $(dirname "${BASH_SOURCE[0]}")/header.sh)"
container=vnc_dev
tag=latest
if [ ! -z $1 ]; then
    container=$1
fi
if [ ! -z $2 ]; then
    tag=$2
fi

docker run ${STANDARD_MOUNTING_ARGUMENTS} ${STANDARD_PORT_FORWARDS} --network=host --restart=unless-stopped -d --name=${container}_${tag} ${container}:${tag}

